apps/items/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create_item$', views.create_item, name='create_item'),
    url(r'^view_item/(?P<item_id>\d+)$', views.view_item, name='view_item'),
    url(r'^update_item/(?P<item_id>\d+)$', views.update_item, name='update_item'),
    url(r'^delete_item/(?P<item_id>\d+)$', views.delete_item, name='delete_item'),
    url(r'^display_add_item$', views.display_add_item, name='display_add_item'),
    url(r'^remove_item$', views.remove_item, name='remove_item'),
    url(r'^add_item_to_fav$', views.add_item_to_fav, name='add_item_to_fav'),
]

apps/login_reg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^logout$', views.logout, name='logout'),
    url(r'^login$', views.login, name='login'),
    url(r'^register$', views.register, name='register'),
    url(r'^$', views.index, name='index')
]

django_with_login/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login_reg.urls', namespace='login_ns')),
    url(r'^items/', include('apps.items.urls', namespace='items_ns')),
]

apps/items/models.py
from __future__ import unicode_literals
from django.db import models
from ..login_reg.models import User

# Create your models here.
class ItemManager(models.Manager):
    def create_item(self, postData, user_id):
        user_name=User.objects.get(id=user_id)
        self.create(name=postData['content'], user=User.objects.get(id=user_id))
        item_id = self.filter().latest('id')
        self.add_to_favorites(item_id.id, user_id)

    def add_to_favorites(self, item_id, user_id):
        item_obj = self.get(id=item_id)
        item_obj.favorites.add(user_id)

    def get_all_data(self, user_id):
        user_data = User.objects.all()
        items_data = self.all()
        current_user = User.objects.get_user_data_from_session(user_id)
        favorites = self.get_favorites(user_id)
        other_items = self.get_other_items(user_id)
        all_data = {
            'users': user_data,
            'items': items_data,
            'current_user': current_user,
            'favorites': favorites,
            'other_items': other_items
        }
        print all_data
        return all_data

    def get_favorites(self, user_id):
        return self.filter(favorites__id=user_id)

    def get_other_items(self, user_id):
        return self.all().exclude(favorites__id=user_id)

    def remove_from_fav(self, item_id, user_id):
        item_obj = self.get(id=item_id)
        user_obj = User.objects.get(id=user_id)
        item_obj.favorites.remove(user_obj)

    def get_item_likers(self, item_id):
        users = User.objects.filter(in_favorites=item_id)
        print users
        return users

    def get_item_data(self, item_id):
        item_data = self.get(id=item_id)
        print item_data
        return item_data

    def is_user(self, item_id, user_id):
        is_true = self.filter(id=item_id,user=User.objects.get(id=user_id))
        return is_true

    def update_item(self, postData, item_id):
        content=postData['content']
        self.filter(id=item_id).update(content=content)

    def delete_item(self, postData, item_id):
        self.filter(id=item_id).delete()


class Item(models.Model):
    name = models.CharField(max_length=150)
    user = models.ForeignKey(User, related_name='user_posts')
    added_by = models.ForeignKey(User, related_name='added_items', null=True)
    favorites = models.ManyToManyField(User, related_name='in_favorites', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ItemManager()

apps/items/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from .models import Item
# Create your views here.
def index(request):
    print(request.session['user_id'])
    all_data = Item.objects.get_all_data(request.session['user_id'])
    context = {
        'data': all_data
    }
    print(all_data['favorites'])
    return render(request, 'items/index.html', context)

def display_add_item(request):
    all_data = Item.objects.get_all_data(request.session['user_id'])
    context = {
        'data': all_data
    }
    return render(request, 'items/add_item.html', context)

def add_item_to_fav(request):
    user_id = request.POST['user_id']
    item_id = request.POST['item_id']
    Item.objects.add_to_favorites(item_id, user_id)
    return redirect('items_ns:index')

def create_item(request):
    if len(request.POST['content']) < 3:
        messages.add_message(request, messages.ERROR, 'Items must be at least 3 characters long.')
        return redirect('items_ns:display_add_item')
    Item.objects.create_item(request.POST, request.session['user_id'])
    return redirect('items_ns:index')

def remove_item(request):
    item_id = request.POST['item_id']
    user_id = request.POST['user_id']
    Item.objects.remove_from_fav(item_id, user_id)
    return redirect('items_ns:index')


def view_item(request, item_id):
    items_info = Item.objects.get_item_data(item_id)
    users = Item.objects.get_item_likers(item_id)
    all_data = Item.objects.get_all_data(request.session['user_id'])
    context = {
        'items_data': items_info,
        'users': users,
        'data': all_data
    }
    return render(request, 'items/item.html', context)
def update_item(request, item_id):
    Item.objects.update_item(request.POST, item_id)
    return redirect('/')

def delete_item(request, item_id):
    Item.objects.delete_item(request.POST, item_id)
    return redirect('/')

apps/items/templates/items/add_item.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" charset="utf-8"></script>
  </head>
  <body>
    <div class="container">
      <div class="errors">
        {% if messages %}
          {% for msg in messages %}
            <p>{{msg}}</p>
          {% endfor %}
        {% endif %}
      </div>
      <div class="row">
        <div class="col-xs-10">
        </div>
        <div class="col-xs-1">
          <form class="" action="{% url 'login_ns:index' %}" method="post">
            {% csrf_token %}
            <input type="submit" name="" value="Home" class='btn btn-primary'>
          </form>
        </div>
        <div class="col-xs-1">
          <form class="" action="{% url 'login_ns:logout' %}" method="post">
            {% csrf_token %}
            <input type="submit" name="" value="Log Out" class='btn btn-danger'>
          </form>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <form class="" action="{% url 'items_ns:create_item'  %}" method="post">
            {% csrf_token %}
            New Item: <input type="text" name="content" value="">
            <input type="submit" name="" value="Add Item" class='btn btn-primary'>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>

apps/items/templates/items/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" charset="utf-8"></script>
  </head>
  <body>
    <div class="container">
      <div class="errors">
        {% if messages %}
          {% for msg in messages %}
            <p>{{msg}}</p>
          {% endfor %}
        {% endif %}
      </div>
      <div class="row">
        <div class="col-xs-10">
          <h3>Welcome, {{data.current_user.first_name}}</h3>
        </div>
        <div class="col-xs-2">
          <form class="" action="{% url 'login_ns:logout' %}" method="post">
            {% csrf_token %}
            <input type="submit" name="" value="Log Out" class='btn btn-danger'>
          </form>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <h2>Your Favorites</h2>
          <table class="table">
            <tr>
              <th>Item</th>
              <th>Added By</th>
              <th>Date Added</th>
              <th>Action</th>
            </tr>
            {% for item in data.favorites %}
              <tr>
                <td><a href="{% url 'items_ns:view_item' item.id %}">{{item.name}}</a></td>
                <td>{{item.user.first_name}}</td>
                <td>{{item.created_at|date:"M d, Y"}}</td>
                <td>{% if not item.added_by.id == request.session.id %}
                  <form class="" action="{% url 'items_ns:delete_item' item.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" name="" value="Delete Item" class="btn btn-danger">
                  </form>
                  {% else %}
                  <form class="" action="{% url 'items_ns:remove_item' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="item_id" value="{{item.id}}">
                    <input type="hidden" name="user_id" value="{{request.session.user_id}}">
                    <input type="submit" name="" value="Remove Item From Favorites" class="btn btn-warning">
                  </form>
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </table>

          <table class="table">
            <tr>
              <th>Item</th>
              <th>Added By</th>
              <th>Date Added</th>
              <th>Action</th>
            </tr>
            {% for item in data.other_items %}
              <tr>
                <td><a href="{% url 'items_ns:view_item' item.id %}">{{item.name}}</a></td>
                <td>{{item.added_by.first_name}}</td>
                <td>{{item.created_at|date:"M d, Y"}}</td>
                <td>
                  <form class="" action="{% url 'items_ns:add_item_to_fav' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="item_id" value="{{item.id}}">
                    <input type="hidden" name="user_id" value="{{request.session.user_id}}">
                    <input type="submit" name="" value="Add Item To Favorites" class="btn btn-primary">
                  </form>

                </td>
              </tr>
            {% endfor %}
          </table>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-3-offset-9">
          <form class="" action="{% url 'items_ns:display_add_item' %}" method="post">
            {% csrf_token %}
            <input type="submit" name="" value="Add Item" class="btn btn-primary">
          </form
        </div>
      </div>
    </div>
  </body>
</html>

apps/items/templates/items/item.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" charset="utf-8"></script>
  </head>
  <body>
    <div class="row">
      <div class="col-xs-10">
      </div>
      <div class="col-xs-1">
        <form class="" action="{% url 'login_ns:index' %}" method="post">
          {% csrf_token %}
          <input type="submit" name="" value="Home" class='btn btn-primary'>
        </form>
      </div>
      <div class="col-xs-1">
        <form class="" action="{% url 'login_ns:logout' %}" method="post">
          {% csrf_token %}
          <input type="submit" name="" value="Log Out" class='btn btn-danger'>
        </form>
      </div>
    </div>
    <h1>{{items_data.name}}</h1>
    <h3>Users Who Like This Item:</h3>
    <ul>
      {% for user in users %}
      <li>{{user.first_name}}</li>
      {% endfor %}
    </ul>


  </body>
</html>