apps/login_reg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^logout$', views.logout, name='logout'),
    url(r'^login$', views.login, name='login'),
    url(r'^register$', views.register, name='register'),
    url(r'^$', views.index, name='index')
]

django_with_login/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login_reg.urls', namespace='login_ns')),
    url(r'^items/', include('apps.items.urls', namespace='items_ns')),
]

apps/login_reg/models.py
from __future__ import unicode_literals
import re
from django.db import models
import bcrypt

# Create your models here.
class UserManager(models.Manager):
    def validate_reg(self, postData):
        # list to hold error messages
        errors = []
        if not len(postData['first_name']) > 2:
            errors.append('First name must be at least 3 characters.')
        if not len(postData['email']) > 2:
            errors.append('User name must be at least 3 characters.')
        if not len(postData['pass1']) > 7:
            errors.append('Password must be at least 8 characters.')
        if not postData['pass1'] == postData['pass2']:
            errors.append('Passwords must match.')
        if not self.check_email(postData):
            errors.append('User name already in use.')
        return errors

    def check_email(self, postData):
        emails = User.objects.filter(email=postData['email'])
        if emails:
            return False
        return True

    def create_user(self, postData):
        User.objects.create(first_name=postData['first_name'], last_name='null', email=postData['email'], password=bcrypt.hashpw(postData['pass1'].encode(), bcrypt.gensalt()))

    def login(self, postData):
        user_data = User.objects.filter(email=postData['email']).first()
        # print(user_obj)
        pwhash = user_data.password.encode()
        if pwhash == bcrypt.hashpw(postData['pass1'].encode(), pwhash):
            return True
        return False

    def set_session(self, postData):
        user_data = User.objects.filter(email=postData['email']).first()
        user_id = user_data.id
        return user_id

    def get_user_data_from_session(self, session_id):
        user_data = User.objects.filter(id=session_id).first()
        print(user_data)
        return user_data



class User(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=200)
    password = models.CharField(max_length=55)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

apps/login_reg/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User, UserManager
from django.core.urlresolvers import reverse

# Create your views here.
def index(request):
    if 'user_id' in request.session:
        messages.add_message(request, messages.ERROR, 'You were already logged in, goof. If you would like to log into or register a new account, please log out first.')
        print('logged in')
        return redirect(reverse('items_ns:index'))
    return render(request, 'login_reg/index.html')
def register(request):
    errors = User.objects.validate_reg(request.POST)
    if len(errors) > 0:
        for error in errors:
            messages.error(request, error)
        return redirect('login_ns:index')

    user_data = User.objects.create_user(request.POST)

    request.session['user_id'] = User.objects.set_session(request.POST)
    return redirect(reverse('items_ns:index'))
def login(request):
    is_email = User.objects.check_email(request.POST)
    if is_email:
         messages.error(request, 'This user name has not been registered.')
         return redirect('login_ns:index')
    is_match = User.objects.login(request.POST)
    if not is_match:
        messages.error(request, 'The user name or password is incorrect.')
        return redirect('login_ns:index')
    request.session['user_id'] = User.objects.set_session(request.POST)
    return redirect(reverse('items_ns:index'))

def logout(request):
    request.session.flush()
    return redirect('/')

apps/login_reg/templates/login_reg/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" charset="utf-8"></script>
</head>

<body>
    <div class="errors">
        {% if messages %} {% for msg in messages %}
        <p>{{msg}}</p>
        {% endfor %} {% endif %}
    </div>
    <div class="col-xs-6">
        <h2>Register:</h2>
        <form class="" action="{% url 'login_ns:register' %}" method="post">
            {% csrf_token %} Name: <input type="text" name="first_name" value=""><br> User Name: <input type="text" name="email" value=""><br> Password:
            <input type="password" name="pass1"
                value=""><br> Confirm Password: <input type="password" name="pass2" value=""><br>
                Date Hired: <input type="text" name="last_name" value="" placeholder='MM/DD/YYYY'><br>
                <input type="submit" name="" value="Register" class="btn btn-primary">
        </form>
    </div>
    <div class="col-xs-6">
        <h2>Login:</h2>
        <form class="" action="{% url 'login_ns:login' %}" method="post">
            {% csrf_token %} User Name: <input type="text" name="email" value=""><br> Password: <input type="password" name="pass1" value=""><br>
            <input type="submit" name="" value="Log In" class="btn btn-primary">
        </form>
    </div>
</body>

</html>